### ISSUE TITLE
Using \N after exiting and restarting results in a function signature mismatch

### ISSUE THREAD

**Issue by treyhunner** [ethanhs/python-wasm#69] opened 2022-03-31 02:16 UTC
Series of steps which reveal the bug:

1. Click `Start REPL` button
2. Type `print("\N{digit nine}")` and hit Enter
3. See that `9` printed out
4. Type `exit()` and hit Enter (to exit the process)
5. Click `Start REPL` button again
6. Type `print("\N{digit nine}")` and hit Enter
7. Watch the process hang and an error message print to the console (**this is the bug**)

![image](https://user-images.githubusercontent.com/285352/160950884-beba91a0-01b9-4266-aea8-f1988d2365fc.png)

Similar series of working steps (notice no `\N{...}` was used)

1. Click `Start REPL` button
2. Type `print("9")` and hit Enter
3. See that `9` printed out
4. Type `exit()` and hit Enter (to exit the process)
5. Click `Start REPL` button again
6. Type `print("9")` and hint Enter
7. See that `9` printed out

![image](https://user-images.githubusercontent.com/285352/160950809-b6044822-84c5-4972-ad50-875c56221b64.png)

---

**Context**

This might seem like a strange bug to care about, but it's causing [my Python pastebin site](https://pym.dev/p) (which now runs Python code in-browser) to fail on some code examples. Specifically the "Run in Browser" button works the first time it's pressed but hangs the second time it's pressed. [Here's a page that demonstrates the issue](https://pym.dev/p/2xzz5/).

**Comment by pmp-p** [comment] 2022-03-31 06:49
i'm definitively not sure but it could be because of running in inspect mode https://github.com/ethanhs/python-wasm/blob/cef91af7ded9ff456eec633f346e085a9ccb038a/browser-ui/index.js#L22 where the interpreter may still persist after the first exit() and take a different code path for init.

**Comment by tiran** [comment] 2022-03-31 13:00
With some additional magic (``-gsource-map`` linker flag and Chromium C/C++ DWARF extension) I was able to pin point the location. The issue is **much** more interesting than I initially thought. In fact you have found a bug in CPython.

```
python.js:219 Uncaught RuntimeError: null function or function signature mismatch
    at _PyUnicode_DecodeUnicodeEscapeInternal (unicodeobject.c:6493:25)
    at decode_unicode_with_escapes (string_parser.c:121:13)
    at _PyPegen_parsestr (string_parser.c:273:1)
    at strings_rule (action_helpers.c:901:20)
    at atom_rule (parser.c:14293:27)
    at primary_rule (parser.c:13916:17)
    at await_primary_rule (parser.c:13666:17)
    at factor_rule (parser.c:13542:29)
    at term_rule (parser.c:13330:17)
    at sum_rule (parser.c:13044:17)
```

**Comment by tiran** [comment] 2022-03-31 13:40
Fixed in https://github.com/python/cpython/pull/32212

**Comment by emmatyping** [comment] 2022-04-17 07:09
I can confirm that this is fixed in the live REPL (which now is up to date!)

**Closed as completed by emmatyping** 2022-04-17 07:09 UTC
